Controle-Estoque-Front/Models/ErrorViewModel.cs
namespace Controle_Estoque_Front.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controle-Estoque-Front/Controllers/CategoriaController.cs
using ControleEstoque.Domain.Models.DataModel;
using Microsoft.AspNetCore.Mvc;
using ControleEstoque.Domain.Enums;

namespace Controle_Estoque_Front.Controllers
{
    public class CategoriaController : Controller
    {
        public IActionResult Index()
        {
            return View(GetListCategorias());
        }

        public IActionResult FormCategoria()
        {
            return View();
        }

        [HttpGet]
        [Route("/Category/View/{Id:Int}", Name = "ViewCategoria")]

        public IActionResult View(int Id)
        {
            var listaCategorias = GetListCategorias();

            var categoria = listaCategorias.Where(c => c.Id.Equals(Id)).FirstOrDefault();

            return View(categoria);
        }

        private List<CategoriaViewModel> GetListCategorias()
        {
            CategoriaViewModel categoriaComida = new CategoriaViewModel();

            categoriaComida.Id = 1;
            categoriaComida.Name = "Comida";
            categoriaComida.Status = StatusEnum.Ativo;

            CategoriaViewModel categoriaEletronico = new CategoriaViewModel();

            categoriaEletronico.Id = 2;
            categoriaEletronico.Name = "Eletronico";
            categoriaEletronico.Status = StatusEnum.Ativo;

            List<CategoriaViewModel> listCategorias = new List<CategoriaViewModel>();
            listCategorias.Add(categoriaComida);
            listCategorias.Add(@categoriaEletronico);

            return listCategorias;

        }
    }
}

Controle-Estoque-Front/Controllers/HomeController.cs
using ControleEstoque.Domain.Models;
using ControleEstoque.Domain.Models.DataModel;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Controle_Estoque_Front.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controle-Estoque-Front/Controllers/MarcaController.cs
using ControleEstoque.Domain.Models.DataModel;
using Microsoft.AspNetCore.Mvc;
using ControleEstoque.Domain.Enums;

namespace Controle_Estoque_Front.Controllers
{
    public class MarcaController : Controller
    {
        public IActionResult Index()
        {
            return View(GetListMarca());
        }

        public IActionResult FormMarca()
        {
            return View();
        }

        [HttpGet]
        [Route("/Marca/View/{Id:Int}", Name = "ViewMarca")]

        public IActionResult View(int Id)
        {
            var listaMarca = GetListMarca();

            var marca = listaMarca.Where(m => m.Id.Equals(Id)).FirstOrDefault();

            return View(marca);
        }

        private List<MarcaViewModel> GetListMarca()
        {
            MarcaViewModel marcaSamsung = new MarcaViewModel();

            marcaSamsung.Id = 1;
            marcaSamsung.Name = "Samsung";
            marcaSamsung.Status = StatusEnum.Ativo;
            
            List<MarcaViewModel> listMarcas = new List<MarcaViewModel>();
            listMarcas.Add(marcaSamsung);

            return listMarcas;

        }
    }
}

Controle-Estoque-Front/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using ControleEstoque.Domain.Models.DataModel;
using ControleEstoque.Domain.Enums;

namespace Controle_Estoque_Front.Controllers
{
    public class ProdutoController : Controller
    {
        public IActionResult Index()
        {
            return View(GetListProdutos());
        }

        public IActionResult FormProduto()
        {
            return View();
        }

        [HttpGet]
        [Route("/Products/View/{Id:Int}", Name = "ViewProduto")]

        public IActionResult View(int Id)
        {
            var listaProdutos = GetListProdutos();

            var produto = listaProdutos.Where(p => p.Id.Equals(Id)).FirstOrDefault();

            return View(produto);
        }

        private List<ProdutoViewModel> GetListProdutos()
        {

            ProdutoViewModel produtoMelancia = new ProdutoViewModel();
            CategoriaViewModel categoriaComida = new CategoriaViewModel();

            categoriaComida.Name = "Comida";
            categoriaComida.Status = StatusEnum.Ativo;

            produtoMelancia.Id = 1;
            produtoMelancia.Name = "Melancia";
            produtoMelancia.Price = 10;
            produtoMelancia.Quantity = 20;
            produtoMelancia.Categoria = categoriaComida;
            produtoMelancia.Description = "Uma Fruta";


            ProdutoViewModel produtoCelular = new ProdutoViewModel();
            CategoriaViewModel categoriaEletronico = new CategoriaViewModel();

            categoriaEletronico.Name = "Eletronicos";
            categoriaEletronico.Status = StatusEnum.Ativo;

            produtoCelular.Id = 2;
            produtoCelular.Name = "Celular";
            produtoCelular.Price = 1000;
            produtoCelular.Quantity = 9;
            produtoCelular.Categoria = categoriaEletronico;
            produtoCelular.Description = "Um Smartphone";

            List<ProdutoViewModel> listProdutos = new List<ProdutoViewModel>();
            listProdutos.Add(produtoMelancia);
            listProdutos.Add(produtoCelular);

            return listProdutos;

        }
    }
}

Controle-Estoque-Front/Views/Categoria/FormCategoria.cshtml
<form>
    <fieldset>
        <legend>Adicionar Nova Categoria</legend>
        <div class="row">

            <div class="col-3">
                <label for="NomeCategoria" class="form-label">Nome da Categoria</label>
                <input type="text" id="NomeCategoria" class="form-control" placeholder="Nome-Categoria">
            </div>

            <div class="col-3">
                <label for="StatusCategoria" class="form-label">Status da Categoria</label>
                <select id="StatusCategoria" class="form-control">
                    <option>Status</option>
                    <option>0-Inativo</option>
                    <option>1-Ativo</option>
                </select>
            </div>

        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

Controle-Estoque-Front/Views/Categoria/Index.cshtml
@using ControleEstoque.Domain.Models.DataModel;

@{
    ViewData["Title"] = "Listagem de Categorias";
}

@model List<CategoriaViewModel>

<h1>@ViewData["Title"]</h1>

<table class="table table-striped table-bordered table-hover border-dark">
  <thead>
    <tr>
      <th scope="col">Nome da Categoria</th>
      <th scope="col">Status da Categoria</th>
    </tr>
  </thead>
  <tbody>
  
    @* <tr>
      <td>Eletronicos</td>
      <td>1</td>
    </tr> *@
 
        @{
            foreach(var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Status</td>
                </tr>
                
            }
        }

  </tbody>
</table>

Controle-Estoque-Front/Views/Categoria/View.cshtml
@using ControleEstoque.Domain.Models.DataModel;

@model CategoriaViewModel

<form>
    <fieldset>
        <legend>Adicionar Nova Categoria</legend>
        <div class="row">

            <div class="col-3">
                <label for="NomeCategoria" class="form-label">Nome da Categoria</label>
                @* <input type="text" id="NomeCategoria" class="form-control" placeholder="Nome-Categoria"> *@
                @Html.DisplayFor(model => model.Name)
            </div>

            <div class="col-3">
                <label for="StatusCategoria" class="form-label">Status da Categoria</label>
                <select id="StatusCategoria" class="form-control">
                    <option>Status</option>
                    <option>0-Inativo</option>
                    <option>1-Ativo</option>
                </select>
            </div>

        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

Controle-Estoque-Front/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Controle-Estoque-Front/Views/Home/Privacy - Cópia.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Controle-Estoque-Front/Views/Marca/FormMarca.cshtml
<form>
    <fieldset>
        <legend>Adicionar Nova Marca</legend>
        <div class="row">

            <div class="col-3">
                <label for="NoemMarca" class="form-label">Nome da Marca</label>
                <input type="text" id="NomeMarca" class="form-control" placeholder="Nome-Marca">
            </div>

            <div class="col-3">
                <label for="StatusDaMarca" class="form-label">Status da Marca</label>
                <select id="StatusMarca" class="form-control">
                    <option>Status</option>
                    <option>0-Inativo</option>
                    <option>1-Ativo</option>
                </select>
            </div>

        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

Controle-Estoque-Front/Views/Marca/Index.cshtml
@using ControleEstoque.Domain.Models.DataModel;

@{
    ViewData["Title"] = "Listagem de Marca";
}

@model List<MarcaViewModel>

<h1>@ViewData["Title"]</h1>

<table class="table table-striped table-bordered table-hover border-dark">
  <thead>
    <tr>
      <th scope="col">Nome da Marca</th>
      <th scope="col">Status da Marca</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
 
        @{
            foreach(var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Status</td>
                    <td>@Html.RouteLink("Visualizar", "ViewMarca", new {Id = item.Id})</td>
                </tr>
                
            }
        }

  </tbody>
</table>

Controle-Estoque-Front/Views/Marca/View.cshtml
@using ControleEstoque.Domain.Models.DataModel;

@model MarcaViewModel

<form>
    <fieldset>
        <legend>Adicionar Nova Categoria</legend>
        <div class="row">

            <div class="col-3">
                <label for="NomeMarca" class="form-label">Nome da Marca</label>
                @* <input type="text" id="NomeMarca" class="form-control" placeholder="Nome-Marca"> *@
                @Html.DisplayFor(model => model.Name)
            </div>

            <div class="col-3">
                <label for="StatusDaMarca" class="form-label">Status da Marca</label>
                <select id="StatusMarca" class="form-control">
                    <option>Status</option>
                    <option>0-Inativo</option>
                    <option>1-Ativo</option>
                </select>
            </div>

        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

Controle-Estoque-Front/Views/Produto/FormProduto.cshtml
<form>
    <fieldset>
        <legend>Adicionar Novo Produto</legend>
        <div class="row">

            <div class="col-3">
                <label for="NomeProduto" class="form-label">Nome do Produto</label>
                <input type="text" id="NomeProduto" class="form-control" placeholder="Nome-Produto">
            </div>

            <div class="col-3">
                <label for="PreçoProduto" class="form-label">Preço do Produto</label>
                <input type="text" id="PreçoProduto" class="form-control" placeholder="Preço-Produto">
            </div>

            <div class="col-3">
                <label for="QuantidadeProduto" class="form-label">Quantidade de Produtos</label>
                <input type="text" id="QuantidadeProduto" class="form-control" placeholder="Quantidade-Produto">
            </div>

        </div>

        <div class="row">

            <div class="col-3">
                <label for="CategoryName" class="form-label">Nome da Categoria</label>
                <select id="CategoryName" class="form-select">
                    <option>Selecione uma categoria</option>
                    <option>Eletronicos</option>
                    <option>Comida</option>
                </select>
            </div>

            <div class="col-3">
                <label for="DescriçãoDoProduto" class="form-label">Descrição do Produto</label>
                <input type="text" id="DescriçãoDoProduto" class="form-control" placeholder="Descrição">
            </div>


        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

Controle-Estoque-Front/Views/Produto/Index.cshtml
@using ControleEstoque.Domain.Models.DataModel;
@{
    ViewData["Title"] = "Listagem de Produtos";
}

@model List<ProdutoViewModel> 

<h1>@ViewData["Title"]</h1>

<table class="table table-striped table-bordered table-hover border-dark">
  <thead>
    <tr>
      <th scope="col">Nome do Produto</th>
      <th scope="col">Preço do Produto</th>
      <th scope="col">Quantidade de Produto</th>
      <th scope="col">Nome da Categoria</th>
      <th scope="col">Descrição do Produto</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  
    @* <tr>
      <td>Celular</td>
      <td>9.999</td>
      <td>9</td>
      <td>Eletronicos</td>
      <td>Um celular eletronico</td>
    </tr> *@

        @{
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Quantity</td>
                    <td>@item.Categoria.Name</td>
                    <td>@item.Description</td>
                    <td>@Html.RouteLink("Visualizar", "ViewProduto", new {Id = item.Id})</td>
                </tr>
            }
        }
        
        

  </tbody>
</table>

Controle-Estoque-Front/Views/Produto/View.cshtml
@using ControleEstoque.Domain.Models.DataModel;


@model ProdutoViewModel

<form>
    <fieldset>
        <legend>Adicionar Novo Produto</legend>
        <div class="row">

            <div class="col-3">
                <label for="NomeProduto" class="form-label">Nome do Produto</label>
                @* <input type="text" id="NomeProduto" class="form-control" placeholder="Nome-Produto"> *@
                @Html.DisplayFor(model => model.Name)
            </div>

            <div class="col-3">
                <label for="PreçoProduto" class="form-label">Preço do Produto</label>
                @* <input type="text" id="PreçoProduto" class="form-control" placeholder="Preço-Produto"> *@
                @Html.DisplayFor(model => model.Price)
            </div>

            <div class="col-3">
                <label for="QuantidadeProduto" class="form-label">Quantidade de Produtos</label>
                @* <input type="text" id="QuantidadeProduto" class="form-control" placeholder="Quantidade-Produto"> *@
                @Html.DisplayFor(model => model.Quantity)
            </div>

        </div>

        <div class="row">

            <div class="col-3">
                <label for="CategoryName" class="form-label">Nome da Categoria</label>
                <select id="CategoryName" class="form-select">
                    <option>Selecione uma categoria</option>
                    <option>Eletronicos</option>
                    <option>Comida</option>
                </select>
            </div>

            <div class="col-3">
                <label for="DescriçãoDoProduto" class="form-label">Descrição do Produto</label>
                @* <input type="text" id="DescriçãoDoProduto" class="form-control" placeholder="Descrição"> *@
                @Html.DisplayFor(model => model.Description)
            </div>


        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

Controle-Estoque-Front/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle_Estoque_Front</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Controle_Estoque_Front.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle_Estoque_Front</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li> *@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Produto
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class ="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Listagem</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="FormProduto">Novo</a></li>
                            </ul>
                        </li>
@*
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        *@</li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categoria
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Listagem</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="FormCategoria">Novo</a></li>
                            </ul>

                            <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Marca
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Listagem</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="FormMarca">Novo</a></li>
                            </ul>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Controle_Estoque_Front - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>